micronaut:
  application:
    name: valkey-poc
  server:
    port: 8080
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  management:
    endpoints:
      all:
        enabled: true
        sensitive: false
      health:
        enabled: true
        details-visible: ANONYMOUS
      metrics:
        enabled: true
      prometheus:
        enabled: true
        sensitive: false
      info:
        enabled: true
        sensitive: false
      beans:
        enabled: true
        sensitive: false
      env:
        enabled: true
        sensitive: false
      loggers:
        enabled: true
        sensitive: false
  tracing:
    zipkin:
      enabled: true
      http:
        url: http://localhost:9411
        sender:
          type: http
    jaeger:
      enabled: false
    brave:
      enabled: true
      http:
        client:
          enabled: true
        server:
          enabled: true

redis:
  uri: redis://localhost:6379
  timeout: 30s
  
logging:
  level:
    com.example: DEBUG
    io.lettuce: INFO
    io.micronaut: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"